### ISSUE TITLE
Regarding resume login with stored token

### ISSUE THREAD

**Issue by successanil** [kenyee/java-ddp-client#10]
I m using ddp lib to login to ddp server via native android app. 
I m facing a strange scenario..
 I log in successfully and get authtoken returned . I saved this authtoken to my local storage. i can subscribe successfully to my lists now. Now After  I try to resume login with my already saved token .. i get phone no verified true returned from server . but after that i can't be able to subscribe to lists again. 

Am i missing something in the flow to resume login with saved token ? .

Thanks

**Comment by tlkiong** [comment]
Please let me know if my assumption of wat you did is wrong: you send your initial auth token to the server to make it "resume".

If this is true, your websocket connection to the server should be closed. Can you verify this?

**Comment by successanil** [comment]
Hello .. 

so you mean to say websocket connection to the server should be closed prior to making call to resume login with token ?
