### ISSUE TITLE
Where can I find the Meteor server app code for testing

### ISSUE THREAD

**Issue by jazeee** [kenyee/java-ddp-client#12]
I am looking at running the Unit tests on this Java DDP client package.
I started down the path of creating a Meteor server app, adding accounts-password, etc, but it seems like it would be easier to use an existing Meteor server app.
Can you point me to one?

I want to look at Java-WebSocket 1.3.0 code. From my past experience, that project has intermittent bugs, like duplicated messages or flaking out when the data payload is larger than some 100KB or so. Curious if you have seen issues. (I've had much better luck with Tyrus Java WebSocket).

Thanks.

**Comment by kenyee** [comment]
@jazeee : you can find the test endpoint here: https://github.com/kenyee/meteor-test-ddp-endpoint
It's running a fairly old version of Meteor, so if you update this library or the endpoint to the latest version, please submit a PR.
I haven't seen any issues w/ Java-WebSocket.

**Comment by jazeee** [comment]
Excellent. Thanks.
I was able to manually migrate the code to Meteor 1.3.5.1 and start the app.
Most tests against Java pass now. 6 failures, but I will work on that now.
I will PR when done. The old Meteor project was really old!

**Comment by jazeee** [comment]
https://github.com/kenyee/meteor-test-ddp-endpoint/pull/1
