### ISSUE TITLE
Java-WebSocket 1.3.3 doesn't exist on maven

### ISSUE THREAD

**Issue by Davide95** [kenyee/java-ddp-client#19]
On maven you've specified
```
<dependency>
   <groupId>org.java-websocket</groupId>
   <artifactId>Java-WebSocket</artifactId>
   <version>1.3.3</version>
   <scope>test</scope>
</dependency>
```
but this version doesn't exist :

> Failed to execute goal on project java-rrw: Could not resolve dependencies for project org.kde.brooklyn:java-rrw:jar:1.0-SNAPSHOT: Failure to find org.java-websocket:java-websocket:jar:1.3.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

 It should be
```
<dependency>
   <groupId>org.java-websocket</groupId>
   <artifactId>Java-WebSocket</artifactId>
   <version>1.3.4</version>
   <scope>test</scope>
</dependency>
```

**Comment by kenyee** [comment]
fixed via PR..thanks Davide.  Artifacts on maven.
