### ISSUE TITLE
Use SSL error?

### ISSUE THREAD

**Issue by tlkiong** [kenyee/java-ddp-client#6]
This is a weird issue which I am not able to pinpoint yet.

It goes like this:
1) On first try to initwebsocket with useSSL = true
2) Can connect and all is fine
3) close websocket
4) 2nd time initwebsocket with useSSL = true
5) Receive error:
    (a) draft org.java_websocket.drafts.Draft_10@7847e63f refuses handshake

Do you have any idea why or what happened?

**Comment by tlkiong** [comment]
I have found the issue.

On the DDPClient.connect(..), if the conection is closed, it will just 
>createWsClient(mMeteorServerAddress);
And this is without the 
> .setWebSocketFactory() to it

**Comment by kenyee** [comment]
1.0.0.2 will have a fix for this. Thanks for finding it.

**Comment by shantanubhadoria** [comment]
Good day,
Is the fix for using ws over ssl out yet? I have a ssl based connection but I don't know how to tell MyDDPState class to use ssl.
Thanks for the help

**Comment by shantanubhadoria** [comment]
I figured it might help if I paste some code

    // My DDPState Class
    public class MyDDPState extends DDPStateSingleton {

       protected static String sMeteorServer = "example.com";
       protected static Integer sMeteorPort = 443;

       private static final String TAG = "MyDDPState";

       private MyDDPState(Context context){
           super(context, sMeteorServer, sMeteorPort);
       }

       public static void initInstance(Context context) {
           if(mInstance == null){
               mInstance = new MyDDPState(context);
           }
       }

       public static MyDDPState getInstance() {
           // Return the instance
           return (MyDDPState) mInstance;
       }
   
       @Override
       protected void createDDPClient() {
           try {
               mDDP = new DDPClient(sMeteorServer, sMeteorPort, true);
           } catch (URISyntaxException e) {
               Log.e(TAG, "Invalid Websocket URL connecting to " + getServerHostname()
                       + ":" + getServerPort());
            }
           getDDP().addObserver(this);
           mDDPState = DDPSTATE.NotLoggedIn;
       }
   
       public void verifyPhone(String phone) {
           Object[] methodArgs = new Object[1];
           methodArgs[0] = phone;
           getDDP().call("requestPhoneVerification", methodArgs);
       }
    }

Also, here is my Application class

    public class MyApplication extends Application {
        private static Context sContext = null;

       @Override
       public void onCreate() {
           super.onCreate();
           MyApplication.sContext = getApplicationContext();
           // Initialize the singletons so their instances
           // are bound to the application process.
           initSingletons();
       }

       private void initSingletons() {
           MyDDPState.initInstance(MyApplication.sContext);
       }
   
       public static Context getAppContext() {
           return MyApplication.sContext;
       }
    }
