### ISSUE TITLE
Class not found: WebSocketClient

### ISSUE THREAD

**Issue by Tim-W** [kenyee/java-ddp-client#8]
Whenever I try to establish a DDPClient, I get the following error.

```Exception in thread "ServerEngine" java.lang.NoClassDefFoundError: org/java_websocket/client/WebSocketClient```

I establish the DDPClient as follows: 

```DDPClient ddp = new DDPClient("localhost", 3000);```

My meteor server is running on localhost:3000. Any help appreciated!

**Comment by tlkiong** [comment]
Are you having all the dependencies that is required for this project?

It seems like you are missing the websocket client jar file

**Comment by Tim-W** [comment]
The java-ddp-client did not include the dependencies, I added them and that fixed it.

This can be closed.
